### ISSUE TITLE
Compilar librerias

### ISSUE THREAD

**Issue by gayoso** [eduardoneira/Macho-Drive#2]
Los .c y .h de mongoose y json estan tirados en la carpeta /src/common, deberian ir los .h en /include (con los de rocksdb) y deberiamos tener librerias compiladas tal vez asi no se compilan cada vez con nuestro codigo (especialmente el json.cpp que tarda un cachito). E incorporar estos cambios al CMakeLists

**Comment by eduardoneira** [comment]
Arreglado, ahi hice todo eso. Me pongo a ver travis y despues commiteo lo q ando laburando
