### ISSUE TITLE
Donde nos fijamos si ya existe un nombre de usuario

### ISSUE THREAD

**Issue by gayoso** [eduardoneira/Macho-Drive#30]
Podriamos hacerlo en el cliente (el cliente deberia pedir al servidor una lista de usuarios, como "GET /users/" ponele), y asi queda como en las pags que apenas clickeas afuera del cuadradito para poner el usuario te dice si ya existe. O sino en el server, y seria como en las pags que cuando pones registrarme se actualiza y te marca en rojo el campo nombre de usuario pq ya existe.

**Comment by eduardoneira** [comment]
Para mi la segunda se ve mas posta, incluso la primera podria ser q actualiza cuando dejes de escribir por 2 segundos, ahi capaz es cuando checkea el usuario no es instantaneo. Yo creo q lo haria en el server pero no se si me entiendes. O sea no se si vale la pena hacer una lista de usuarios y pasarsela pero veamos q opinan los demas

**Comment by gayoso** [comment]
La base tira error si se intenta crear un usuario que ya existe.
