### ISSUE TITLE
Error al ejecutar servidor

### ISSUE THREAD

**Issue by gfusca** [eduardoneira/Macho-Drive#40]
Cuando quiero ejecutar el ejecutable del servidor, generado luego de la compilación ocurre un error

radagast@radagast00:/tmp/Macho-Drive/server/build$ ./Server 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Backtrace(gdb)
#6  0x00007ffff7b34f8d in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000000000543af3 in allocate (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/4.8/ext/new_allocator.h:104
#8  _M_allocate (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:168
#9  _M_create_storage (__n=<optimized out>, this=0x7fffffffd658) at /usr/include/c++/4.8/bits/stl_vector.h:181
#10 _Vector_base (__a=..., __n=<optimized out>, this=0x7fffffffd658) at /usr/include/c++/4.8/bits/stl_vector.h:136
#11 vector (__x=..., this=0x7fffffffd658) at /usr/include/c++/4.8/bits/stl_vector.h:312
#12 rocksdb::ColumnFamilyOptions::ColumnFamilyOptions (this=0x7fffffffd590, options=...) at util/options.cc:192
#13 0x00000000004d8039 in rocksdb::DB::Open (options=..., dbname=..., dbptr=0x8a5d10) at db/db_impl.cc:4208
#14 0x00000000004af3a6 in DatabaseRocksDB::open (this=0x8a5d00) at /tmp/Macho-Drive/server/src/DatabaseRocksDB.cpp:35
#15 0x00000000004a067a in HandlerManager::HandlerManager (this=0x8a5cc0) at /tmp/Macho-Drive/server/src/HandlerManager.cpp:24
#16 0x00000000004b989f in Server::Server (this=0x7fffffffdd30) at /tmp/Macho-Drive/server/src/Server.cpp:8
#17 0x00000000004b3253 in main () at /tmp/Macho-Drive/server/src/main.cpp:15

**Comment by gayoso** [comment]
Me olvide completamente, este error me salia en la laptop cuando trataba de correrlo tambien. Y es raro porque sale en el Open de RocksDB, cuando todavia no hicimos nada (pero los tests de rocksdb me pasan todos). Pero con la version 3.13.1 de RocksDB (que era la mas nueva a principio del cuatri) no pasa, [aca](https://github.com/eduardoneira/Macho-Drive/releases/tag/v1.1.1) la inclui en el repo y actualice el INSTALL.md (dejo abierto el ticket por si no anda, yo lo probe y me funciono)

**Comment by gfusca** [comment]
Ok. Ahí lo probé con la versión de rocksdb que subieron al repositorio y funcionó. Aclaren eso en el archivo INSTALL.md (versión de rocks db minima).

Pueden cerrar el bug.
