### ISSUE TITLE
Crear handlers que manejen los requests del server

### ISSUE THREAD

**Issue by NKeklikian** [eduardoneira/Macho-Drive#5]
Debería haber cuatro por lo menos: SignUp, Login, SendFile y GetFile. La idea es que hereden de EventHandler.

**Comment by gayoso** [comment]
ahora que lo pense un poco mas esto de mandar el handlerType o eventType desde el cliente es medio pasarse REST por los huevos. Tal vez deberiamos definir que combinaciones de metodo + uri representan cada evento y trabajar con eso. Por ejemplo, POST usuarios/ (en el cuerpo deberia decir username, etc) quiere decir SignUp, POST archivos/usuario/ quiere decir subir un archivo, PUT archivos/usuario quiere decir actualizar, etc

**Comment by NKeklikian** [comment]
100% de acuerdo

**Comment by eduardoneira** [comment]
Edu approves
