### ISSUE TITLE
Fallan 4 Unit Tests y los tests de Python

### ISSUE THREAD

**Issue by gayoso** [eduardoneira/Macho-Drive#61]
son todos errores en cheques de como funciona borrar archivos, seguro es por la papelera de reciclaje (los chequeos que fallan son cosas como borrar un archivo y ver q la cantidad de archivos disminuye en 1, cuando en realidad ahora es una baja logica nada mas)

**Comment by eduardoneira** [comment]
Arrglado los unit test y python  test
