### ISSUE TITLE
Definir cómo vamos a transferir los archivos.

### ISSUE THREAD

**Issue by NKeklikian** [eduardoneira/Macho-Drive#7]
Una idea es manejarlos como tiras de bytes y guardarnos las extensiones.

**Comment by gayoso** [comment]
Esta podria ser una organizacion de los registros de la base de datos. Cada seccion seria una column family, asi esta organizada la informacion y podemos iterar o hacer busquedas dentro de cada column family. Algunas cosas que no estoy seguro: que tan costoso es acceder con una clave cuyo valor es muy grande? Si fuera costoso, se podria separar los metadatos de un archivo de su contenido (con los metadatos se guarda la clave que referencia al contenido), pero supongo que eso lo podemos probar mas adelante cuando este implementado esto. Fijense que onda.

EDIT: subi el arch al repo pq se veia feo aca
